# Generated by Django 4.0 on 2021-12-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.FilePathField(verbose_name='/model')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.dataset')),
            ],
        ),
    ]
