# Generated by Django 4.0 on 2021-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='path',
            field=models.FilePathField(path='model/'),
        ),
    ]
